gameplay.time_set(gameplay.time(DAY))
for index in range(20):
    agent.set_item(IRON_BLOCK, 4, 1)
    agent.place(FORWARD)
    agent.move(UP, 1)
    agent.place(FORWARD)
    agent.move(LEFT, 1)
    agent.place(FORWARD)
    agent.move(RIGHT, 2)
    agent.place(FORWARD)
    agent.move(LEFT, 1)
    agent.move(UP, 1)
    agent.set_item(JACK_O_LANTERN, 1, 1)
    agent.place(FORWARD)
    agent.move(DOWN, 2)

    agent.move(BACK, 1)
    agent.move(UP, 1)
    agent.move(LEFT, 2)
    agent.interact(FORWARD)
    loops.pause(1000)
    agent.interact(FORWARD)
    agent.move(RIGHT, 2)
    agent.move(DOWN, 1)
    agent.move(FORWARD, 1)
